### ISSUE TITLE
Question: How to send additional data other than uuid, identifier?

### ISSUE THREAD

**Issue by ghost** [philipheinser/beaconbroadcast#2]
How to send additional data other than uuid, identifier?

**Comment by philipheinser** [comment]
@jo2010 what do you mean by additional data?

**Comment by ghost** [comment]
@philipheinser in beacon data, along with uuid, i want to send some additional custom data related to my application.

**Comment by philipheinser** [comment]
@jo2010 Beacons just broadcast an uuid. The technology is not for transferring data.
